spring:
  datasource:
    username: root
    password: 
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 30000
      auto-commit: true 
      max-lifetime: 1800000
      idle-timeout: 300000
      maximum-pool-size: 5

server:
  port: 8011
  cache: 
    type: redis
    redis:
      time-to-live: 30000 #缓存超时时间ms
      cache-null-values: false #是否缓存空值
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 10000
    
base:
  redis:
    expireTime: 3600
    
logging:
  level:
    root: debug
